# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseTube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='institute',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='courseTube.Student'),
        ),
        migrations.AddField(
            model_name='institute',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institute',
            name='registeredBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseTube.Student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ManyToManyField(blank=True, to='courseTube.Faculty'),
        ),
    ]
