# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseTube', '0002_auto_20160903_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instituteProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
