# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseTube', '0005_auto_20160903_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
