# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseTube', '0006_auto_20160903_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
