# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseTube', '0007_institute_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
