# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseTube', '0010_auto_20160904_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursesInstitute', to='courseTube.Institute'),
        ),
    ]
