# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courseTube', '0013_auto_20160904_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
