# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseTube', '0014_review_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='facility',
            field=models.ManyToManyField(blank=True, to='courseTube.Facility'),
        ),
    ]
