# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseTube', '0015_auto_20160904_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='courseTube.Tag'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='weekdays',
            field=models.ManyToManyField(related_name='weekdays', to='courseTube.WeekDays'),
        ),
    ]
