# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseTube', '0017_auto_20160904_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tag01',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='tag02',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='tag03',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='tag04',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='tag05',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='tag06',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='tag07',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='tag08',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='tag09',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='tag10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='tag11',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='tag12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='tag13',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='tag14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='tag15',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='tag16',
            field=models.IntegerField(default=0),
        ),
    ]
