# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseTube', '0018_auto_20160904_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='tag02',
            new_name='tag1',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='tag04',
            new_name='tag2',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='tag06',
            new_name='tag3',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='tag08',
            new_name='tag4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tag01',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tag03',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tag05',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tag07',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tag09',
        ),
        migrations.AddField(
            model_name='student',
            name='tag5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='tag6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='tag7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='tag8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='tag9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='tag11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='tag13',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='tag15',
            field=models.IntegerField(default=0),
        ),
    ]
