# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseTube', '0020_auto_20160904_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='logo',
            field=models.CharField(default='http://cometoart.com/wp-content/uploads/2016/03/pojo-placeholder-2.png', max_length=100),
        ),
    ]
